### ISSUE TITLE
Another test

### ISSUE THREAD

**Issue by mcolyer** [mcolyer-sandbox/acme#3]
asdf

**Comment by mcolyer** [comment]
Well I think something different.

**Comment by mcolyer** [comment]
What about this?

**Comment by mcolyer** [comment]
What about this?

**Comment by mcolyer** [comment]
Image?

**Comment by mcolyer** [comment]
asdf

**Comment by mcolyer** [comment]
Another one

**Comment by mcolyer** [comment]
Don't reply to this.

**Comment by mcolyer** [comment]
asdf

**Comment by mcolyer** [comment]
Don't reply

**Comment by mcolyer** [comment]
@mcolyer help?

**Comment by mcolyer** [comment]
asdf

**Comment by mcolyer** [comment]
@mcolyer help?

**Comment by mcolyer** [comment]
@kdaigle help?

**Comment by mcolyer** [comment]
@kdaigle are you out?

**Comment by mcolyer** [comment]
@kdaigle asdf

**Comment by mcolyer** [comment]
@kdaigle tests

**Comment by mcolyer** [comment]
@kdaigle test

**Comment by mcolyer** [comment]
@kdaigle test

**Comment by mcolyer** [comment]
@kdaigle tests

**Comment by kdaigle** [comment]
@kdaigle well, I have a very tricky issue. Do you know if I should pay @mcolyer for his time or just give him a cupcake?

**Comment by kdaigle** [comment]
@kdaigle how much do you like Node?

**Comment by mcolyer** [comment]
@kdaigle how should I prioritize this feature request?

**Comment by mcolyer** [comment]
@kdaigle how many features have you worked on?

**Comment by mcolyer** [comment]
@kdaigle node js ruby github

**Comment by mcolyer** [comment]
@kdaigle node js ruby github

**Comment by mcolyer** [comment]
@kdaigle node js ruby github

**Comment by mcolyer** [comment]
@kdaigle node js ruby github

**Comment by mcolyer** [comment]
@kdaigle how should I prioritize this feature request?
